name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Build Site
        run: |
          mkdir -p public
          cp *.html public/
          cp *.css public/
          echo "Files to deploy:"
          ls -la public/
      
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'
          retention-days: 1
      
      - uses: actions/deploy-pages@v4
        id: deployment