name: Deploy GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Prepare Deployment
        run: |
          # Create docs directory if it doesn't exist
          mkdir -p docs
          
          # Copy necessary files to docs/
          cp styles2.css post_template2.html docs/
          
          # Verify files exist
          ls -la docs/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs/'
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
