name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Prepare Files
        shell: cmd
        run: |
          mkdir docs 2>nul
          if exist styles2.css copy styles2.css docs\
          if exist post_template2.html copy post_template2.html docs\
          echo Files copied to docs:
          dir docs
      
      - uses: actions/upload-pages-artifact@v2
        with:
          path: 'docs'
      
      - uses: actions/deploy-pages@v2